Add constructor to allow esbuild customizations
sorrycc/esbuild-webpack-plugin pull request #20
Opened 2020-09-02 03:40 UTC by dionshihk

## Reason

The latest ESBuild uglifies my JavaScript codes into undesired targets, e.g: **ESNext**.
It fails to execute in some old browsers, with some new syntax features, e.g: **nullish coalescing**.

As ESBuild already supports its own options, therefore, I hope this webpack plugin can also pass down the customized options to the ESBuild.

## Changes
- Add constructor options (optional, exported as `ESBuildPluginOptions` interface), to allow esbuild customizations.
Option details can refer to: https://github.com/evanw/esbuild

- Tune class internal typings and make it more normalized.
- Update README on related usages

2020-09-06 03:00 UTC, sorrycc requested changes

2020-09-06 03:00 UTC, sorrycc commented on src/index.ts
> +        ...this.options,
don't modify this, options (minify, sourcemap and sourcefile) should not be modified.

2020-09-06 03:00 UTC, sorrycc commented on .gitignore
> +/.idea
/.idea and /.vscode should be added to ~/.gitignore_global

2020-09-07 02:15 UTC, dionshihk commented
Thanks @sorrycc for feedback.
I've updated the constructor usage, and also exclude these options by TypeScript definition.

2020-09-07 02:42 UTC, merged